version: "3.7"

services:
  jenkins:
    image: sixeyed/psod-pipelines-jenkins:dotnet-20.04
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./dotnet
